
var menus = [
	{
		id:'fundDetails',
		cls:'icon_01',
		pressedCls:'icon_01_press',
		title:'资金明细',
		view:'hrmobile.public.myhome.fundDetails'
	},
	{
		id:'rechargeAndwithdraw',
		cls:'icon_02',
		pressedCls:'icon_02_press',
		title:'充值提现',
		view:'hrmobile.public.myhome.rechargeAndwithdraw'
	},
	{
		id:'safety',
		cls:'icon_03',
		pressedCls:'icon_03_press',
		title:'安全设置',
		view:'hrmobile.public.myhome.safety'
	}
	,
	{
		id:'bankCard',
		cls:'icon_04',
		pressedCls:'icon_04_press',
		title:'银行卡设置',
		view:'hrmobile.public.myhome.bankCard'
	},
	{
		id:'record',
		cls:'icon_05',
		pressedCls:'icon_05_press',
		title:'交易记录',
		view:'hrmobile.public.myhome.record'
	},
	{
		id:'investProduct',
		cls:'icon_06',
		pressedCls:'icon_06_press',
		title:'投资产品',
		view:'hrmobile.public.myhome.investProduct'
	}
	,
	{
		id:'news',
		cls:'icon_07',
		pressedCls:'icon_07_press',
		title:'站内消息',
		view:'hrmobile.public.myhome.news'
	},
	{
		id:'loanList',
		cls:'icon_08',
		pressedCls:'icon_08_press',
		title:'我要贷款',
		view:'hrmobile.public.myhome.loanList'
	}/*,
	
	{
		id:'invitePromotion',
		cls:'icon_08',
		pressedCls:'icon_08_press',
		title:'推广链接',
		view:'hrmobile.public.myhome.invitePromotion'
	}*/
];
